<%-- 
    Document   : index
    Created on : Sep 13, 2010, 2:16:56 PM
    Author     : Adewale Azeez
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">

<html>
<head>
    <TITLE>E-Manifest Interface</TITLE>
    <META HTTP-EQUIV="Refresh" CONTENT="0;URL=pages/login.jsp">
</head>

<body>
<p>Loading ..............</p>
</body>
</html>