package net.emanifest.hibernate;
// Generated Dec 5, 2010 1:42:23 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Activities generated by hbm2java
 */
@Entity
@Table(name="activities"
    ,catalog="emanifest"
)
public class Activities  implements java.io.Serializable {


     private ActivitiesId id;
     private String descriptions;

    public Activities() {
    }

    public Activities(ActivitiesId id, String descriptions) {
       this.id = id;
       this.descriptions = descriptions;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="userEmail", column=@Column(name="userEmail", nullable=false, length=50) ), 
        @AttributeOverride(name="activityDate", column=@Column(name="activityDate", nullable=false, length=10) ), 
        @AttributeOverride(name="activityTime", column=@Column(name="activityTime", nullable=false, length=10) ) } )
    public ActivitiesId getId() {
        return this.id;
    }
    
    public void setId(ActivitiesId id) {
        this.id = id;
    }
    
    @Column(name="descriptions", nullable=false, length=250)
    public String getDescriptions() {
        return this.descriptions;
    }
    
    public void setDescriptions(String descriptions) {
        this.descriptions = descriptions;
    }




}


