package net.emanifest.hibernate;
// Generated Dec 5, 2010 1:42:23 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ActivitiesId generated by hbm2java
 */
@Embeddable
public class ActivitiesId  implements java.io.Serializable {


     private String userEmail;
     private String activityDate;
     private String activityTime;

    public ActivitiesId() {
    }

    public ActivitiesId(String userEmail, String activityDate, String activityTime) {
       this.userEmail = userEmail;
       this.activityDate = activityDate;
       this.activityTime = activityTime;
    }
   

    @Column(name="userEmail", nullable=false, length=50)
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    @Column(name="activityDate", nullable=false, length=10)
    public String getActivityDate() {
        return this.activityDate;
    }
    
    public void setActivityDate(String activityDate) {
        this.activityDate = activityDate;
    }

    @Column(name="activityTime", nullable=false, length=10)
    public String getActivityTime() {
        return this.activityTime;
    }
    
    public void setActivityTime(String activityTime) {
        this.activityTime = activityTime;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ActivitiesId) ) return false;
		 ActivitiesId castOther = ( ActivitiesId ) other; 
         
		 return ( (this.getUserEmail()==castOther.getUserEmail()) || ( this.getUserEmail()!=null && castOther.getUserEmail()!=null && this.getUserEmail().equals(castOther.getUserEmail()) ) )
 && ( (this.getActivityDate()==castOther.getActivityDate()) || ( this.getActivityDate()!=null && castOther.getActivityDate()!=null && this.getActivityDate().equals(castOther.getActivityDate()) ) )
 && ( (this.getActivityTime()==castOther.getActivityTime()) || ( this.getActivityTime()!=null && castOther.getActivityTime()!=null && this.getActivityTime().equals(castOther.getActivityTime()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUserEmail() == null ? 0 : this.getUserEmail().hashCode() );
         result = 37 * result + ( getActivityDate() == null ? 0 : this.getActivityDate().hashCode() );
         result = 37 * result + ( getActivityTime() == null ? 0 : this.getActivityTime().hashCode() );
         return result;
   }   


}


