package net.emanifest.hibernate;
// Generated Dec 5, 2010 1:42:23 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Eregistrationrequest generated by hbm2java
 */
@Entity
@Table(name="eregistrationrequest"
    ,catalog="emanifest"
)
public class Eregistrationrequest  implements java.io.Serializable {


     private Integer serialno;
     private String registryNumber;
     private Date departureDate;
     private String customsOfficeCode;
     private Integer totalNumberOfBols;
     private Integer totalNumberOfContainers;
     private Integer totalNumberOfPackages;
     private Double totalGrossMass;

    public Eregistrationrequest() {
    }

    public Eregistrationrequest(String registryNumber, Date departureDate, String customsOfficeCode, Integer totalNumberOfBols, Integer totalNumberOfContainers, Integer totalNumberOfPackages, Double totalGrossMass) {
       this.registryNumber = registryNumber;
       this.departureDate = departureDate;
       this.customsOfficeCode = customsOfficeCode;
       this.totalNumberOfBols = totalNumberOfBols;
       this.totalNumberOfContainers = totalNumberOfContainers;
       this.totalNumberOfPackages = totalNumberOfPackages;
       this.totalGrossMass = totalGrossMass;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="serialno", unique=true, nullable=false)
    public Integer getSerialno() {
        return this.serialno;
    }
    
    public void setSerialno(Integer serialno) {
        this.serialno = serialno;
    }
    
    @Column(name="Registry_Number", length=17)
    public String getRegistryNumber() {
        return this.registryNumber;
    }
    
    public void setRegistryNumber(String registryNumber) {
        this.registryNumber = registryNumber;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="Departure_Date", length=10)
    public Date getDepartureDate() {
        return this.departureDate;
    }
    
    public void setDepartureDate(Date departureDate) {
        this.departureDate = departureDate;
    }
    
    @Column(name="Customs_Office_Code", length=4)
    public String getCustomsOfficeCode() {
        return this.customsOfficeCode;
    }
    
    public void setCustomsOfficeCode(String customsOfficeCode) {
        this.customsOfficeCode = customsOfficeCode;
    }
    
    @Column(name="Total_Number_of_Bols")
    public Integer getTotalNumberOfBols() {
        return this.totalNumberOfBols;
    }
    
    public void setTotalNumberOfBols(Integer totalNumberOfBols) {
        this.totalNumberOfBols = totalNumberOfBols;
    }
    
    @Column(name="Total_Number_of_Containers")
    public Integer getTotalNumberOfContainers() {
        return this.totalNumberOfContainers;
    }
    
    public void setTotalNumberOfContainers(Integer totalNumberOfContainers) {
        this.totalNumberOfContainers = totalNumberOfContainers;
    }
    
    @Column(name="Total_Number_of_Packages")
    public Integer getTotalNumberOfPackages() {
        return this.totalNumberOfPackages;
    }
    
    public void setTotalNumberOfPackages(Integer totalNumberOfPackages) {
        this.totalNumberOfPackages = totalNumberOfPackages;
    }
    
    @Column(name="Total_Gross_Mass", precision=22, scale=0)
    public Double getTotalGrossMass() {
        return this.totalGrossMass;
    }
    
    public void setTotalGrossMass(Double totalGrossMass) {
        this.totalGrossMass = totalGrossMass;
    }




}


