package net.emanifest.hibernate;
// Generated Dec 5, 2010 1:42:23 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TwmBol generated by hbm2java
 */
@Entity
@Table(name="twm_bol"
    ,catalog="emanifest"
)
public class TwmBol  implements java.io.Serializable {


     private Integer serialno;
     private String registryNumber;
     private Date departureDate;
     private String bolReference;
     private String customsOfficeCode;
     private Integer lineNumber;
     private String previousDocumentReference;
     private String bolNature;
     private String uniqueCarrierReference;
     private Integer totalNumberOfContainers;
     private Integer totalGrossMassManifested;
     private Integer volumeInCubicMeters;
     private String bolTypeCode;
     private String exporterCode;
     private String exporterName;
     private String exporterAddress;
     private String consigneeCode;
     private String consigneeName;
     private String consigneeAddress;
     private String notifyCode;
     private String notifyName;
     private String notifyAddress;
     private String placeOfLoadingCode;
     private String placeOfUnloadingCode;
     private String packageTypeCode;
     private Integer numberOfPackages;
     private String shippingMarks;
     private String goodsDescription;
     private Integer freightValue;
     private String freightCurrencyCode;
     private String freightIndicatorCode;
     private Integer customsValue;
     private String customsCurrencyCode;
     private Integer transportValue;
     private String transportCurrencyCode;
     private Integer insuranceValue;
     private String insuranceCurrencyCode;
     private Integer numberOfSeals;
     private String marksOfSeals;
     private String sealingPartyCode;
     private String generalInformation;
     private String locationCode;
     private String locationInformation;
     private String containerIdentification;
     private Integer containerNumber;
     private String containerTypeCode;
     private String emptyFullIndicator;
     private String marksOfSeals1;
     private String marksOfSeals2;
     private String marksOfSeals3;
     private String containerSealingPartyCode;
     private Date entryDate;
     private String containerContent;

    public TwmBol() {
    }

    public TwmBol(String registryNumber, Date departureDate, String bolReference, String customsOfficeCode, Integer lineNumber, String previousDocumentReference, String bolNature, String uniqueCarrierReference, Integer totalNumberOfContainers, Integer totalGrossMassManifested, Integer volumeInCubicMeters, String bolTypeCode, String exporterCode, String exporterName, String exporterAddress, String consigneeCode, String consigneeName, String consigneeAddress, String notifyCode, String notifyName, String notifyAddress, String placeOfLoadingCode, String placeOfUnloadingCode, String packageTypeCode, Integer numberOfPackages, String shippingMarks, String goodsDescription, Integer freightValue, String freightCurrencyCode, String freightIndicatorCode, Integer customsValue, String customsCurrencyCode, Integer transportValue, String transportCurrencyCode, Integer insuranceValue, String insuranceCurrencyCode, Integer numberOfSeals, String marksOfSeals, String sealingPartyCode, String generalInformation, String locationCode, String locationInformation, String containerIdentification, Integer containerNumber, String containerTypeCode, String emptyFullIndicator, String marksOfSeals1, String marksOfSeals2, String marksOfSeals3, String containerSealingPartyCode, Date entryDate, String containerContent) {
       this.registryNumber = registryNumber;
       this.departureDate = departureDate;
       this.bolReference = bolReference;
       this.customsOfficeCode = customsOfficeCode;
       this.lineNumber = lineNumber;
       this.previousDocumentReference = previousDocumentReference;
       this.bolNature = bolNature;
       this.uniqueCarrierReference = uniqueCarrierReference;
       this.totalNumberOfContainers = totalNumberOfContainers;
       this.totalGrossMassManifested = totalGrossMassManifested;
       this.volumeInCubicMeters = volumeInCubicMeters;
       this.bolTypeCode = bolTypeCode;
       this.exporterCode = exporterCode;
       this.exporterName = exporterName;
       this.exporterAddress = exporterAddress;
       this.consigneeCode = consigneeCode;
       this.consigneeName = consigneeName;
       this.consigneeAddress = consigneeAddress;
       this.notifyCode = notifyCode;
       this.notifyName = notifyName;
       this.notifyAddress = notifyAddress;
       this.placeOfLoadingCode = placeOfLoadingCode;
       this.placeOfUnloadingCode = placeOfUnloadingCode;
       this.packageTypeCode = packageTypeCode;
       this.numberOfPackages = numberOfPackages;
       this.shippingMarks = shippingMarks;
       this.goodsDescription = goodsDescription;
       this.freightValue = freightValue;
       this.freightCurrencyCode = freightCurrencyCode;
       this.freightIndicatorCode = freightIndicatorCode;
       this.customsValue = customsValue;
       this.customsCurrencyCode = customsCurrencyCode;
       this.transportValue = transportValue;
       this.transportCurrencyCode = transportCurrencyCode;
       this.insuranceValue = insuranceValue;
       this.insuranceCurrencyCode = insuranceCurrencyCode;
       this.numberOfSeals = numberOfSeals;
       this.marksOfSeals = marksOfSeals;
       this.sealingPartyCode = sealingPartyCode;
       this.generalInformation = generalInformation;
       this.locationCode = locationCode;
       this.locationInformation = locationInformation;
       this.containerIdentification = containerIdentification;
       this.containerNumber = containerNumber;
       this.containerTypeCode = containerTypeCode;
       this.emptyFullIndicator = emptyFullIndicator;
       this.marksOfSeals1 = marksOfSeals1;
       this.marksOfSeals2 = marksOfSeals2;
       this.marksOfSeals3 = marksOfSeals3;
       this.containerSealingPartyCode = containerSealingPartyCode;
       this.entryDate = entryDate;
       this.containerContent = containerContent;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="serialno", unique=true, nullable=false)
    public Integer getSerialno() {
        return this.serialno;
    }
    
    public void setSerialno(Integer serialno) {
        this.serialno = serialno;
    }
    
    @Column(name="Registry_Number", length=17)
    public String getRegistryNumber() {
        return this.registryNumber;
    }
    
    public void setRegistryNumber(String registryNumber) {
        this.registryNumber = registryNumber;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="Departure_Date", length=10)
    public Date getDepartureDate() {
        return this.departureDate;
    }
    
    public void setDepartureDate(Date departureDate) {
        this.departureDate = departureDate;
    }
    
    @Column(name="Bol_Reference", length=17)
    public String getBolReference() {
        return this.bolReference;
    }
    
    public void setBolReference(String bolReference) {
        this.bolReference = bolReference;
    }
    
    @Column(name="Customs_Office_Code", length=4)
    public String getCustomsOfficeCode() {
        return this.customsOfficeCode;
    }
    
    public void setCustomsOfficeCode(String customsOfficeCode) {
        this.customsOfficeCode = customsOfficeCode;
    }
    
    @Column(name="Line_Number")
    public Integer getLineNumber() {
        return this.lineNumber;
    }
    
    public void setLineNumber(Integer lineNumber) {
        this.lineNumber = lineNumber;
    }
    
    @Column(name="Previous_Document_Reference", length=17)
    public String getPreviousDocumentReference() {
        return this.previousDocumentReference;
    }
    
    public void setPreviousDocumentReference(String previousDocumentReference) {
        this.previousDocumentReference = previousDocumentReference;
    }
    
    @Column(name="Bol_Nature", length=2)
    public String getBolNature() {
        return this.bolNature;
    }
    
    public void setBolNature(String bolNature) {
        this.bolNature = bolNature;
    }
    
    @Column(name="Unique_Carrier_Reference", length=35)
    public String getUniqueCarrierReference() {
        return this.uniqueCarrierReference;
    }
    
    public void setUniqueCarrierReference(String uniqueCarrierReference) {
        this.uniqueCarrierReference = uniqueCarrierReference;
    }
    
    @Column(name="Total_Number_of_Containers")
    public Integer getTotalNumberOfContainers() {
        return this.totalNumberOfContainers;
    }
    
    public void setTotalNumberOfContainers(Integer totalNumberOfContainers) {
        this.totalNumberOfContainers = totalNumberOfContainers;
    }
    
    @Column(name="Total_Gross_Mass_Manifested")
    public Integer getTotalGrossMassManifested() {
        return this.totalGrossMassManifested;
    }
    
    public void setTotalGrossMassManifested(Integer totalGrossMassManifested) {
        this.totalGrossMassManifested = totalGrossMassManifested;
    }
    
    @Column(name="Volume_in_Cubic_Meters")
    public Integer getVolumeInCubicMeters() {
        return this.volumeInCubicMeters;
    }
    
    public void setVolumeInCubicMeters(Integer volumeInCubicMeters) {
        this.volumeInCubicMeters = volumeInCubicMeters;
    }
    
    @Column(name="BOL_Type_Code", length=3)
    public String getBolTypeCode() {
        return this.bolTypeCode;
    }
    
    public void setBolTypeCode(String bolTypeCode) {
        this.bolTypeCode = bolTypeCode;
    }
    
    @Column(name="Exporter_Code", length=17)
    public String getExporterCode() {
        return this.exporterCode;
    }
    
    public void setExporterCode(String exporterCode) {
        this.exporterCode = exporterCode;
    }
    
    @Column(name="Exporter_Name", length=35)
    public String getExporterName() {
        return this.exporterName;
    }
    
    public void setExporterName(String exporterName) {
        this.exporterName = exporterName;
    }
    
    @Column(name="Exporter_Address", length=150)
    public String getExporterAddress() {
        return this.exporterAddress;
    }
    
    public void setExporterAddress(String exporterAddress) {
        this.exporterAddress = exporterAddress;
    }
    
    @Column(name="Consignee_Code", length=17)
    public String getConsigneeCode() {
        return this.consigneeCode;
    }
    
    public void setConsigneeCode(String consigneeCode) {
        this.consigneeCode = consigneeCode;
    }
    
    @Column(name="Consignee_Name", length=35)
    public String getConsigneeName() {
        return this.consigneeName;
    }
    
    public void setConsigneeName(String consigneeName) {
        this.consigneeName = consigneeName;
    }
    
    @Column(name="Consignee_Address", length=150)
    public String getConsigneeAddress() {
        return this.consigneeAddress;
    }
    
    public void setConsigneeAddress(String consigneeAddress) {
        this.consigneeAddress = consigneeAddress;
    }
    
    @Column(name="Notify_Code", length=17)
    public String getNotifyCode() {
        return this.notifyCode;
    }
    
    public void setNotifyCode(String notifyCode) {
        this.notifyCode = notifyCode;
    }
    
    @Column(name="Notify_Name", length=35)
    public String getNotifyName() {
        return this.notifyName;
    }
    
    public void setNotifyName(String notifyName) {
        this.notifyName = notifyName;
    }
    
    @Column(name="Notify_Address", length=150)
    public String getNotifyAddress() {
        return this.notifyAddress;
    }
    
    public void setNotifyAddress(String notifyAddress) {
        this.notifyAddress = notifyAddress;
    }
    
    @Column(name="Place_of_Loading_Code", length=5)
    public String getPlaceOfLoadingCode() {
        return this.placeOfLoadingCode;
    }
    
    public void setPlaceOfLoadingCode(String placeOfLoadingCode) {
        this.placeOfLoadingCode = placeOfLoadingCode;
    }
    
    @Column(name="Place_of_Unloading_Code", length=5)
    public String getPlaceOfUnloadingCode() {
        return this.placeOfUnloadingCode;
    }
    
    public void setPlaceOfUnloadingCode(String placeOfUnloadingCode) {
        this.placeOfUnloadingCode = placeOfUnloadingCode;
    }
    
    @Column(name="Package_Type_Code", length=17)
    public String getPackageTypeCode() {
        return this.packageTypeCode;
    }
    
    public void setPackageTypeCode(String packageTypeCode) {
        this.packageTypeCode = packageTypeCode;
    }
    
    @Column(name="Number_of_Packages")
    public Integer getNumberOfPackages() {
        return this.numberOfPackages;
    }
    
    public void setNumberOfPackages(Integer numberOfPackages) {
        this.numberOfPackages = numberOfPackages;
    }
    
    @Column(name="Shipping_Marks", length=350)
    public String getShippingMarks() {
        return this.shippingMarks;
    }
    
    public void setShippingMarks(String shippingMarks) {
        this.shippingMarks = shippingMarks;
    }
    
    @Column(name="Goods_Description", length=175)
    public String getGoodsDescription() {
        return this.goodsDescription;
    }
    
    public void setGoodsDescription(String goodsDescription) {
        this.goodsDescription = goodsDescription;
    }
    
    @Column(name="Freight_Value")
    public Integer getFreightValue() {
        return this.freightValue;
    }
    
    public void setFreightValue(Integer freightValue) {
        this.freightValue = freightValue;
    }
    
    @Column(name="Freight_Currency_Code", length=3)
    public String getFreightCurrencyCode() {
        return this.freightCurrencyCode;
    }
    
    public void setFreightCurrencyCode(String freightCurrencyCode) {
        this.freightCurrencyCode = freightCurrencyCode;
    }
    
    @Column(name="Freight_Indicator_Code", length=3)
    public String getFreightIndicatorCode() {
        return this.freightIndicatorCode;
    }
    
    public void setFreightIndicatorCode(String freightIndicatorCode) {
        this.freightIndicatorCode = freightIndicatorCode;
    }
    
    @Column(name="Customs_Value")
    public Integer getCustomsValue() {
        return this.customsValue;
    }
    
    public void setCustomsValue(Integer customsValue) {
        this.customsValue = customsValue;
    }
    
    @Column(name="Customs_Currency_Code", length=3)
    public String getCustomsCurrencyCode() {
        return this.customsCurrencyCode;
    }
    
    public void setCustomsCurrencyCode(String customsCurrencyCode) {
        this.customsCurrencyCode = customsCurrencyCode;
    }
    
    @Column(name="Transport_Value")
    public Integer getTransportValue() {
        return this.transportValue;
    }
    
    public void setTransportValue(Integer transportValue) {
        this.transportValue = transportValue;
    }
    
    @Column(name="Transport_Currency_Code", length=3)
    public String getTransportCurrencyCode() {
        return this.transportCurrencyCode;
    }
    
    public void setTransportCurrencyCode(String transportCurrencyCode) {
        this.transportCurrencyCode = transportCurrencyCode;
    }
    
    @Column(name="Insurance_Value")
    public Integer getInsuranceValue() {
        return this.insuranceValue;
    }
    
    public void setInsuranceValue(Integer insuranceValue) {
        this.insuranceValue = insuranceValue;
    }
    
    @Column(name="Insurance_Currency_Code", length=3)
    public String getInsuranceCurrencyCode() {
        return this.insuranceCurrencyCode;
    }
    
    public void setInsuranceCurrencyCode(String insuranceCurrencyCode) {
        this.insuranceCurrencyCode = insuranceCurrencyCode;
    }
    
    @Column(name="Number_of_Seals")
    public Integer getNumberOfSeals() {
        return this.numberOfSeals;
    }
    
    public void setNumberOfSeals(Integer numberOfSeals) {
        this.numberOfSeals = numberOfSeals;
    }
    
    @Column(name="Marks_of_Seals", length=20)
    public String getMarksOfSeals() {
        return this.marksOfSeals;
    }
    
    public void setMarksOfSeals(String marksOfSeals) {
        this.marksOfSeals = marksOfSeals;
    }
    
    @Column(name="Sealing_Party_Code", length=3)
    public String getSealingPartyCode() {
        return this.sealingPartyCode;
    }
    
    public void setSealingPartyCode(String sealingPartyCode) {
        this.sealingPartyCode = sealingPartyCode;
    }
    
    @Column(name="General_Information", length=70)
    public String getGeneralInformation() {
        return this.generalInformation;
    }
    
    public void setGeneralInformation(String generalInformation) {
        this.generalInformation = generalInformation;
    }
    
    @Column(name="Location_Code", length=17)
    public String getLocationCode() {
        return this.locationCode;
    }
    
    public void setLocationCode(String locationCode) {
        this.locationCode = locationCode;
    }
    
    @Column(name="Location_Information", length=35)
    public String getLocationInformation() {
        return this.locationInformation;
    }
    
    public void setLocationInformation(String locationInformation) {
        this.locationInformation = locationInformation;
    }
    
    @Column(name="Container_Identification", length=17)
    public String getContainerIdentification() {
        return this.containerIdentification;
    }
    
    public void setContainerIdentification(String containerIdentification) {
        this.containerIdentification = containerIdentification;
    }
    
    @Column(name="Container_Number")
    public Integer getContainerNumber() {
        return this.containerNumber;
    }
    
    public void setContainerNumber(Integer containerNumber) {
        this.containerNumber = containerNumber;
    }
    
    @Column(name="Container_Type_Code", length=4)
    public String getContainerTypeCode() {
        return this.containerTypeCode;
    }
    
    public void setContainerTypeCode(String containerTypeCode) {
        this.containerTypeCode = containerTypeCode;
    }
    
    @Column(name="Empty_Full_Indicator", length=3)
    public String getEmptyFullIndicator() {
        return this.emptyFullIndicator;
    }
    
    public void setEmptyFullIndicator(String emptyFullIndicator) {
        this.emptyFullIndicator = emptyFullIndicator;
    }
    
    @Column(name="Marks_of_Seals_1", length=10)
    public String getMarksOfSeals1() {
        return this.marksOfSeals1;
    }
    
    public void setMarksOfSeals1(String marksOfSeals1) {
        this.marksOfSeals1 = marksOfSeals1;
    }
    
    @Column(name="Marks_of_Seals_2", length=10)
    public String getMarksOfSeals2() {
        return this.marksOfSeals2;
    }
    
    public void setMarksOfSeals2(String marksOfSeals2) {
        this.marksOfSeals2 = marksOfSeals2;
    }
    
    @Column(name="Marks_of_Seals_3", length=10)
    public String getMarksOfSeals3() {
        return this.marksOfSeals3;
    }
    
    public void setMarksOfSeals3(String marksOfSeals3) {
        this.marksOfSeals3 = marksOfSeals3;
    }
    
    @Column(name="Container_Sealing_Party_Code", length=3)
    public String getContainerSealingPartyCode() {
        return this.containerSealingPartyCode;
    }
    
    public void setContainerSealingPartyCode(String containerSealingPartyCode) {
        this.containerSealingPartyCode = containerSealingPartyCode;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="entryDate", length=10)
    public Date getEntryDate() {
        return this.entryDate;
    }
    
    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }
    
    @Column(name="Container_Content", length=2000)
    public String getContainerContent() {
        return this.containerContent;
    }
    
    public void setContainerContent(String containerContent) {
        this.containerContent = containerContent;
    }




}


