package net.emanifest.hibernate;
// Generated Dec 5, 2010 1:42:23 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TwmManifest generated by hbm2java
 */
@Entity
@Table(name="twm_manifest"
    ,catalog="emanifest"
)
public class TwmManifest  implements java.io.Serializable {


     private Integer serialno;
     private String registryNumber;
     private Date departureDate;
     private String customsOfficeCode;
     private String masterInformation;
     private Date lastDischargeDate;
     private Date dateOfArrival;
     private String timeOfArrival;
     private String placeOfDepartureCode;
     private String placeOfDestinationCode;
     private String carrierCode;
     private String carrierName;
     private String carrierAddress;
     private String nameOfTransporter;
     private String placeOfTransporter;
     private String modeOfTransportCode;
     private String nationalityOfTransporterCode;
     private String registrationNumber;
     private Date registrationDate;
     private Integer grossTonnage;
     private Integer netTonnage;
     private Date entryDate;

    public TwmManifest() {
    }

    public TwmManifest(String registryNumber, Date departureDate, String customsOfficeCode, String masterInformation, Date lastDischargeDate, Date dateOfArrival, String timeOfArrival, String placeOfDepartureCode, String placeOfDestinationCode, String carrierCode, String carrierName, String carrierAddress, String nameOfTransporter, String placeOfTransporter, String modeOfTransportCode, String nationalityOfTransporterCode, String registrationNumber, Date registrationDate, Integer grossTonnage, Integer netTonnage, Date entryDate) {
       this.registryNumber = registryNumber;
       this.departureDate = departureDate;
       this.customsOfficeCode = customsOfficeCode;
       this.masterInformation = masterInformation;
       this.lastDischargeDate = lastDischargeDate;
       this.dateOfArrival = dateOfArrival;
       this.timeOfArrival = timeOfArrival;
       this.placeOfDepartureCode = placeOfDepartureCode;
       this.placeOfDestinationCode = placeOfDestinationCode;
       this.carrierCode = carrierCode;
       this.carrierName = carrierName;
       this.carrierAddress = carrierAddress;
       this.nameOfTransporter = nameOfTransporter;
       this.placeOfTransporter = placeOfTransporter;
       this.modeOfTransportCode = modeOfTransportCode;
       this.nationalityOfTransporterCode = nationalityOfTransporterCode;
       this.registrationNumber = registrationNumber;
       this.registrationDate = registrationDate;
       this.grossTonnage = grossTonnage;
       this.netTonnage = netTonnage;
       this.entryDate = entryDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="serialno", unique=true, nullable=false)
    public Integer getSerialno() {
        return this.serialno;
    }
    
    public void setSerialno(Integer serialno) {
        this.serialno = serialno;
    }
    
    @Column(name="Registry_Number", length=17)
    public String getRegistryNumber() {
        return this.registryNumber;
    }
    
    public void setRegistryNumber(String registryNumber) {
        this.registryNumber = registryNumber;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="Departure_Date", length=10)
    public Date getDepartureDate() {
        return this.departureDate;
    }
    
    public void setDepartureDate(Date departureDate) {
        this.departureDate = departureDate;
    }
    
    @Column(name="Customs_Office_Code", length=4)
    public String getCustomsOfficeCode() {
        return this.customsOfficeCode;
    }
    
    public void setCustomsOfficeCode(String customsOfficeCode) {
        this.customsOfficeCode = customsOfficeCode;
    }
    
    @Column(name="Master_Information", length=35)
    public String getMasterInformation() {
        return this.masterInformation;
    }
    
    public void setMasterInformation(String masterInformation) {
        this.masterInformation = masterInformation;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="Last_Discharge_Date", length=10)
    public Date getLastDischargeDate() {
        return this.lastDischargeDate;
    }
    
    public void setLastDischargeDate(Date lastDischargeDate) {
        this.lastDischargeDate = lastDischargeDate;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="Date_of_Arrival", length=10)
    public Date getDateOfArrival() {
        return this.dateOfArrival;
    }
    
    public void setDateOfArrival(Date dateOfArrival) {
        this.dateOfArrival = dateOfArrival;
    }
    
    @Column(name="Time_of_Arrival", length=10)
    public String getTimeOfArrival() {
        return this.timeOfArrival;
    }
    
    public void setTimeOfArrival(String timeOfArrival) {
        this.timeOfArrival = timeOfArrival;
    }
    
    @Column(name="Place_of_Departure_Code", length=5)
    public String getPlaceOfDepartureCode() {
        return this.placeOfDepartureCode;
    }
    
    public void setPlaceOfDepartureCode(String placeOfDepartureCode) {
        this.placeOfDepartureCode = placeOfDepartureCode;
    }
    
    @Column(name="Place_of_Destination_Code", length=5)
    public String getPlaceOfDestinationCode() {
        return this.placeOfDestinationCode;
    }
    
    public void setPlaceOfDestinationCode(String placeOfDestinationCode) {
        this.placeOfDestinationCode = placeOfDestinationCode;
    }
    
    @Column(name="Carrier_Code", length=17)
    public String getCarrierCode() {
        return this.carrierCode;
    }
    
    public void setCarrierCode(String carrierCode) {
        this.carrierCode = carrierCode;
    }
    
    @Column(name="Carrier_Name", length=35)
    public String getCarrierName() {
        return this.carrierName;
    }
    
    public void setCarrierName(String carrierName) {
        this.carrierName = carrierName;
    }
    
    @Column(name="Carrier_Address", length=35)
    public String getCarrierAddress() {
        return this.carrierAddress;
    }
    
    public void setCarrierAddress(String carrierAddress) {
        this.carrierAddress = carrierAddress;
    }
    
    @Column(name="Name_of_Transporter", length=27)
    public String getNameOfTransporter() {
        return this.nameOfTransporter;
    }
    
    public void setNameOfTransporter(String nameOfTransporter) {
        this.nameOfTransporter = nameOfTransporter;
    }
    
    @Column(name="Place_of_Transporter", length=35)
    public String getPlaceOfTransporter() {
        return this.placeOfTransporter;
    }
    
    public void setPlaceOfTransporter(String placeOfTransporter) {
        this.placeOfTransporter = placeOfTransporter;
    }
    
    @Column(name="Mode_of_Transport_Code", length=3)
    public String getModeOfTransportCode() {
        return this.modeOfTransportCode;
    }
    
    public void setModeOfTransportCode(String modeOfTransportCode) {
        this.modeOfTransportCode = modeOfTransportCode;
    }
    
    @Column(name="Nationality_of_Transporter_Code", length=3)
    public String getNationalityOfTransporterCode() {
        return this.nationalityOfTransporterCode;
    }
    
    public void setNationalityOfTransporterCode(String nationalityOfTransporterCode) {
        this.nationalityOfTransporterCode = nationalityOfTransporterCode;
    }
    
    @Column(name="Registration_Number", length=35)
    public String getRegistrationNumber() {
        return this.registrationNumber;
    }
    
    public void setRegistrationNumber(String registrationNumber) {
        this.registrationNumber = registrationNumber;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="Registration_Date", length=10)
    public Date getRegistrationDate() {
        return this.registrationDate;
    }
    
    public void setRegistrationDate(Date registrationDate) {
        this.registrationDate = registrationDate;
    }
    
    @Column(name="Gross_Tonnage")
    public Integer getGrossTonnage() {
        return this.grossTonnage;
    }
    
    public void setGrossTonnage(Integer grossTonnage) {
        this.grossTonnage = grossTonnage;
    }
    
    @Column(name="Net_Tonnage")
    public Integer getNetTonnage() {
        return this.netTonnage;
    }
    
    public void setNetTonnage(Integer netTonnage) {
        this.netTonnage = netTonnage;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="entryDate", length=10)
    public Date getEntryDate() {
        return this.entryDate;
    }
    
    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }




}


