package net.emanifest.hibernate;
// Generated Dec 5, 2010 1:42:23 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    ,catalog="emanifest"
)
public class Users  implements java.io.Serializable {


     private Integer serialno;
     private String userName;
     private String userPassword;
     private String firstName;
     private String lastName;
     private String active;

    public Users() {
    }

    public Users(String userName, String userPassword, String firstName, String lastName, String active) {
       this.userName = userName;
       this.userPassword = userPassword;
       this.firstName = firstName;
       this.lastName = lastName;
       this.active = active;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="serialno", unique=true, nullable=false)
    public Integer getSerialno() {
        return this.serialno;
    }
    
    public void setSerialno(Integer serialno) {
        this.serialno = serialno;
    }
    
    @Column(name="userName", length=100)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    
    @Column(name="userPassword", length=50)
    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }
    
    @Column(name="firstName", length=50)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    
    @Column(name="lastName", length=50)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    
    @Column(name="active", length=10)
    public String getActive() {
        return this.active;
    }
    
    public void setActive(String active) {
        this.active = active;
    }




}


