package net.emanifest.hibernate;
// Generated Dec 5, 2010 1:42:23 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Xmlfolders generated by hbm2java
 */
@Entity
@Table(name="xmlfolders"
    ,catalog="emanifest"
)
public class Xmlfolders  implements java.io.Serializable {


     private Integer serialno;
     private String manifest;
     private String bol;
     private String registration;
     private String batchfile;

    public Xmlfolders() {
    }

    public Xmlfolders(String manifest, String bol, String registration, String batchfile) {
       this.manifest = manifest;
       this.bol = bol;
       this.registration = registration;
       this.batchfile = batchfile;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="serialno", unique=true, nullable=false)
    public Integer getSerialno() {
        return this.serialno;
    }
    
    public void setSerialno(Integer serialno) {
        this.serialno = serialno;
    }
    
    @Column(name="manifest", length=1000)
    public String getManifest() {
        return this.manifest;
    }
    
    public void setManifest(String manifest) {
        this.manifest = manifest;
    }
    
    @Column(name="bol", length=1000)
    public String getBol() {
        return this.bol;
    }
    
    public void setBol(String bol) {
        this.bol = bol;
    }
    
    @Column(name="registration", length=1000)
    public String getRegistration() {
        return this.registration;
    }
    
    public void setRegistration(String registration) {
        this.registration = registration;
    }
    
    @Column(name="batchfile", length=1000)
    public String getBatchfile() {
        return this.batchfile;
    }
    
    public void setBatchfile(String batchfile) {
        this.batchfile = batchfile;
    }




}


